data_loading:
  plates:
    plates_data_path: ["/home/labs/amit/noamsh/data/mm_2023/Blueprint_MM_Plates_MARS_24_03_24.csv", "/home/labs/amit/noamsh/data/mm_2023/Blueprint_MM_Plates_SPID_24_03_24.csv"] # ["/home/labs/amit/noamsh/data/mm_2023/2024_2_13_MARS.tsv", "/home/labs/amit/noamsh/data/mm_2023/2024_2_13_SPID.tsv"]
    plate_id_column_name: Amp.Batch.ID
  sc_sequencing:
    sc_sequencing_data_dir: ["/home/labs/amit/shuangyi/Project_MM_2023/scdata_MARS",  "/home/labs/amit/eyald/sc_pipeline/scdb_v4_human/output/umi.tab"] #"/home/labs/amit/shuangyi/Project_MM_2023/scdata_SPID"]
annotation:
  annotations_file_name: "/home/labs/amit/noamsh/data/mm_2023/cells/cells_annotation_20240410.csv" # 'None' - to no load annotaions
  cell_id_columns_name: 'cID'
  patient_id_column_name: 'None' #'Weizmann.Code'
  cell_type_columns: 'Populations'
pp:
  mitochondrial_gene_patterns: [ "^MT-", "^MTMR", "^MTND", "^MTRN", "^MRPS", "^MRPL" ]
  blacklist_genes_pattern_list: [ "^ERCC-","^MTMR","^MTND","^MTRN","^HSP","^MRPS","^MRPL", "^IGJ","^IGH","^IGK", "^IGL",
                                  "^DNAJ","^IGD","^JCHAIN", "^MALAT1", "^XIST", "^HBA1", "^HBA2", "^HBB", "^HBBP1",
                                  "^HBD", "^HBE1", "^HBG1", "^HBG2", "^HBM", "^HBQ1", "^HBZ", "^HBZP1" ]
  min_num_cells_per_gene: 3
  min_num_genes_per_cell: 100
  min_num_counts_per_cell: 400
  max_pct_mt_genes_pre_cell: 40
sc_classification:
  gene_selection_patterns_blacklist: [ "^AC[0-9]+", "^AL[0-9]+", "^AP[0-9]+", "^AD[0-9]+", "^AF[0-9]+", "-AS[0-9]?$",
                                       "^MIR[0-9]+", "^LINC[0-9]+", "^MT", "^sno", "^ATP","^HIST", "^HLA-", "\\.", "-" ]
  use_shuang_var_genes: MARS_SPID_combined # "MARS_SPID_combined" ,"MARS_SPID_common", None
outputs:
  output_dir: /home/labs/amit/noamsh/repos/MM_2023/outputs
  logging_file_name: log.log
  loaded_adata_file_name: raw_adata.h5ad
  processed_adata_file_name: pp_adata.h5ad
  scvi_model_prefix: scvi_model
